version: '3'

services:

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - 6333:6333
    volumes:
      - qdrant-storage:/qdrant/storage

volumes:
  mongodb-data:
  qdrant-storage: